export * from './userActions';
export * from './leaguesActions';
export * from './gamesActions';
export * from './startGameActions';
export const CONSTANTS = {
    REQUEST_USER: "REQUEST_USER",
    USER_SUCCESS: "USER_SUCCESS",
    GET_USER_ERROR: "GET_USER_ERROR",
    REQUEST_LEAGUES: "REQUEST_LEAGUES",
    LEAGUES_SUCCESS: "LEAGUES_SUCCESS",
    GET_LEAGUES_ERROR: "GET_LEAGUES_ERROR",
    REQUEST_NEXT_GAMES: "REQUEST_NEXT_GAMES",
    NEXT_GAMES_SUCCESS: "NEXT_GAMES_SUCCESS",
    NEXT_GAMES_ERROR: "NEXT_GAMES_ERROR",
    ARRANGE_GAME: "ARRANGE_GAME",
    ARRANGE_GAME_ERROR: "ARRANGE_GAME_ERROR",
    REQUEST_START_GAME: "REQUEST_START_GAME",
    START_GAME_SUCCESS: "START_GAME_SUCCESS",
    START_GAME_ERROR: "START_GAME_ERROR",
    REQUEST_FIRST_TEAM: "REQUEST_FIRST_TEAM",
    FIRST_TEAM_SUCCESS: "FIRST_TEAM_SUCCES",
    FIRST_TEAM_ERROR: "FIRST_TEAM_ERROR",
    REQUEST_SECOND_TEAM: "REQUEST_SECOND_TEAM",
    SECOND_TEAM_SUCCESS: "SECOND_TEAM_SUCCES",
    SECOND_TEAM_ERROR: "SECOND_TEAM_ERROR",
}